keys:
  - &hey_mbp16 age1hhvghmqevnnrea4lzsyxfcg92jvamkhn53jxtaq07sfhl4a4deeskw2ucj
  - &hey_mbp13 age1pavfgyp5lcdsqkwkm9qcymnf6e66pmm8pjdd6g9nu522ats0tcgq9z7v5u
  - &server_box age168py5d2f8yp6a9vl36vq29wcc0veyhw3c4tzxfghadfm47dzufls7l3x8c
  - &server_txcdhub age1ax29xwck20m3rm4eyssccgaa8jvwvrstc20u2u200nckuq7lpy8sguyyds
  - &server_thunk age1n57xxrvlargmrhyfancquz339afcashjagsyutg6k7au02k6xumsnfe3gm
  - &server_txshhub age1u7gla5fxa0mr33nwxsg0qv9yv9c2vvwp449r5elx79ez68ld7ukqs2z4ce
creation_rules:
  - path_regex: secrets/homelab_txcdhub.yaml
    key_groups:
      - age:
        - *hey_mbp16
        - *hey_mbp13
        - *server_txcdhub
  - path_regex: secrets/homelab_txshhub.yaml
    key_groups:
      - age:
        - *hey_mbp16
        - *hey_mbp13
        - *server_box
        - *server_txshhub
  - path_regex: secrets/homelab_box.yaml
    key_groups:
      - age:
        - *hey_mbp16
        - *hey_mbp13
        - *server_box
  - path_regex: secrets/homelab_thunk.yaml
    key_groups:
      - age:
        - *hey_mbp16
        - *hey_mbp13
        - *server_box
        - *server_thunk

